### ISSUE TITLE
切换页面布局之后导航按钮不显示

### ISSUE THREAD

**Issue by zongyanglaobiao** [Liu-code3/luckyColor-admin#90]
切换布局之后，无法再切回去，因为找不到设置按钮
![image](https://github.com/user-attachments/assets/bda82941-f1b6-4d94-a5c0-8c4eeeb06451)

**Comment by Liu-code3** [comment]
感谢您宝贵的issue，因为您切换的是全屏显示的布局，然后全屏切换对应的按钮还未想好如何安放。临时方案已经推送(https://github.com/Liu-code3/luckyColor-admin/pull/91)，请拉取最新代码
